<a href="https://colab.research.google.com/github/srivastava071/flyrank-ml-internship/blob/main/work/notebooks/w05_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-08 — Capstone Modeling Lane

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/srivastava071/flyrank-ml-internship/blob/main/work/notebooks/w05_model.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [ ]:
%pip -q install duckdb huggingface_hub

In [ ]:
import os
import getpass
import duckdb

HF_TOKEN = os.environ.get("HF_TOKEN")

if not HF_TOKEN:
    try:
        from google.colab import userdata
        HF_TOKEN = userdata.get("HF_TOKEN")
    except Exception:
        pass

HF_TOKEN = HF_TOKEN or getpass.getpass(
    "Paste your Hugging Face READ token (hf_...): "
)

con = duckdb.connect()

con.execute(
    f"CREATE OR REPLACE SECRET hf "
    f"(TYPE huggingface, TOKEN '{HF_TOKEN}')"
)

REL = "hf://datasets/FlyRank/internship-warehouse"

TABLES = {
    "dim_clients":
        f"read_parquet('{REL}/dim_clients.parquet')",

    "dim_content":
        f"read_parquet('{REL}/dim_content.parquet')",

    "fact_daily":
        f"read_parquet('{REL}/fact_content_daily_performance/**/*.parquet')",

    "fact_query_90d":
        f"read_parquet('{REL}/fact_content_query_90d.parquet')",
}

print("DuckDB connected successfully.")
print("Tables:", list(TABLES.keys()))

Paste your Hugging Face READ token (hf_...): ··········
DuckDB connected successfully.
Tables: ['dim_clients', 'dim_content', 'fact_daily', 'fact_query_90d']

In [ ]:
for name, src in TABLES.items():
    n = con.sql(
        f"SELECT COUNT(*) FROM {src}"
    ).fetchone()[0]

    print(f"{name:20} {n:,} rows")

dim_clients          104 rows
dim_content          519,606 rows

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

fact_daily           78,835,655 rows
fact_query_90d       2,414,248 rows

## 1. Method choice and why

I will use a Random Forest classifier as the first learned model for this lane. The target is `is_declining`, and the model will use the same six pre-decision features used by the Week-4 baseline: previous 30-day impressions, previous 30-day clicks, previous 30-day average position, visible query count, top query share, and content age.

Random Forest is appropriate because the relationships between these signals and decline may be nonlinear and may involve interactions between features. It also provides feature importance information that can help with interpretation.

The model is used as decision-support rather than as an automatic content action. Its performance will be compared with the Week-4 rule on the same evaluation population and metric.

In [ ]:
print("Method: Random Forest Classifier")
print("Task: Classification")
print("Target: meaningful impression decline")
print("Comparison: Week-4 rule-based baseline")

Method: Random Forest Classifier
Task: Classification
Target: meaningful impression decline
Comparison: Week-4 rule-based baseline

In [ ]:
feature_cols = [
    "previous_30d_impressions",
    "previous_30d_clicks",
    "previous_30d_avg_position",
    "visible_query_count",
    "top_query_share",
    "age_days"
]

print("Model features:")
for col in feature_cols:
    print("-", col)

print("\nNumber of features:", len(feature_cols))

Model features:
- previous_30d_impressions
- previous_30d_clicks
- previous_30d_avg_position
- visible_query_count
- top_query_share
- age_days

Number of features: 6

## 2. Split design

I will use a client-grouped holdout on the March decision dataset. The March evaluation population is the same population used by my Week-4 baseline, where features are calculated from the February 2026 window and the outcome is observed during March 2026.

Clients will be divided into training and test groups so that content from the same client does not appear in both groups. This reduces the risk that the model learns client-specific patterns and gives a more realistic test of whether the learned signals generalize to unseen clients.

The Week-4 baseline does not require training, so its score will also be evaluated on the same held-out test clients. This keeps the model and baseline comparison on the same evaluation rows.

In [ ]:
date_check = con.sql(f"""
SELECT
    MIN(report_date) AS earliest_date,
    MAX(report_date) AS latest_date,
    COUNT(DISTINCT report_date) AS number_of_days
FROM {TABLES['fact_daily']}
""").df()

date_check

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  earliest_date latest_date  number_of_days
0    2025-01-27  2026-06-30             520

In [ ]:
content_schema = con.sql(f"""
DESCRIBE SELECT *
FROM {TABLES['dim_content']}
""").df()

content_schema

                   column_name column_type null   key default extra
0               client_hash_id     VARCHAR  YES  None    None  None
1              content_hash_id     VARCHAR  YES  None    None  None
2              keyword_hash_id     VARCHAR  YES  None    None  None
3                  url_hash_id     VARCHAR  YES  None    None  None
4           keyword_char_count      BIGINT  YES  None    None  None
5          keyword_token_count      BIGINT  YES  None    None  None
6               url_char_count      BIGINT  YES  None    None  None
7         content_created_date        DATE  YES  None    None  None
8         content_updated_date        DATE  YES  None    None  None
9                 content_type     VARCHAR  YES  None    None  None
10               search_volume      BIGINT  YES  None    None  None
11                 competition      DOUBLE  YES  None    None  None
12           competition_level     VARCHAR  YES  None    None  None
13                         cpc      DOUBLE  YES  None    None  None
14                 main_intent     VARCHAR  YES  None    None  None
15                   backlinks      BIGINT  YES  None    None  None
16              category_count      BIGINT  YES  None    None  None
17        keyword_created_date        DATE  YES  None    None  None
18               provider_used     VARCHAR  YES  None    None  None
19                  model_used     VARCHAR  YES  None    None  None
20                  char_count      BIGINT  YES  None    None  None
21                  word_count      BIGINT  YES  None    None  None
22         last_optimized_date        DATE  YES  None    None  None
23  optimization_eligible_date        DATE  YES  None    None  None
24                is_published     BOOLEAN  YES  None    None  None
25                  is_deleted     BOOLEAN  YES  None    None  None

In [ ]:
daily_schema = con.sql(f"""
DESCRIBE SELECT *
FROM {TABLES['fact_daily']}
""").df()

daily_schema

                 column_name column_type null   key default extra
0                report_date        DATE  YES  None    None  None
1             client_hash_id     VARCHAR  YES  None    None  None
2            content_hash_id     VARCHAR  YES  None    None  None
3             client_has_gsc     BOOLEAN  YES  None    None  None
4             client_has_ga4     BOOLEAN  YES  None    None  None
5         gsc_data_available     BOOLEAN  YES  None    None  None
6         ga4_data_available     BOOLEAN  YES  None    None  None
7            gsc_impressions      BIGINT  YES  None    None  None
8                 gsc_clicks      BIGINT  YES  None    None  None
9           gsc_sum_position      BIGINT  YES  None    None  None
10          gsc_avg_position      DOUBLE  YES  None    None  None
11             ga4_pageviews      BIGINT  YES  None    None  None
12              ga4_sessions      BIGINT  YES  None    None  None
13                 ga4_users      BIGINT  YES  None    None  None
14      ga4_engaged_sessions      BIGINT  YES  None    None  None
15  ga4_total_engagement_sec      BIGINT  YES  None    None  None
16          sessions_organic      BIGINT  YES  None    None  None
17           sessions_direct      BIGINT  YES  None    None  None
18         sessions_referral      BIGINT  YES  None    None  None
19           sessions_social      BIGINT  YES  None    None  None
20             sessions_paid      BIGINT  YES  None    None  None
21               sessions_ai      BIGINT  YES  None    None  None
22                ai_chatgpt      BIGINT  YES  None    None  None
23             ai_perplexity      BIGINT  YES  None    None  None
24                 ai_gemini      BIGINT  YES  None    None  None
25                ai_copilot      BIGINT  YES  None    None  None
26                 ai_claude      BIGINT  YES  None    None  None
27                   ai_meta      BIGINT  YES  None    None  None
28                  ai_other      BIGINT  YES  None    None  None
29             scroll_events      BIGINT  YES  None    None  None
30                     month     VARCHAR  YES  None    None  None

In [ ]:
june_check = con.sql(f"""
SELECT
    MIN(report_date) AS june_start,
    MAX(report_date) AS june_end,
    COUNT(*) AS june_rows
FROM {TABLES['fact_daily']}
WHERE report_date >= DATE '2026-06-01'
  AND report_date < DATE '2026-07-01'
""").df()

june_check

  june_start   june_end  june_rows
0 2026-06-01 2026-06-30   11694072

In [ ]:
import pandas as pd
import numpy as np

march_data = con.sql(f"""
WITH previous_window AS (
    SELECT
        f.client_hash_id,
        f.content_hash_id,
        SUM(f.gsc_impressions) AS previous_30d_impressions,
        SUM(f.gsc_clicks) AS previous_30d_clicks,
        AVG(f.gsc_avg_position) AS previous_30d_avg_position
    FROM {TABLES['fact_daily']} f
    WHERE f.report_date >= DATE '2026-02-01'
      AND f.report_date < DATE '2026-03-01'
      AND f.gsc_data_available IS TRUE
    GROUP BY
        f.client_hash_id,
        f.content_hash_id
),

march_window AS (
    SELECT
        f.client_hash_id,
        f.content_hash_id,
        SUM(f.gsc_impressions) AS march_impressions
    FROM {TABLES['fact_daily']} f
    WHERE f.report_date >= DATE '2026-03-01'
      AND f.report_date < DATE '2026-04-01'
      AND f.gsc_data_available IS TRUE
    GROUP BY
        f.client_hash_id,
        f.content_hash_id
),

query_signals AS (
    SELECT
        content_hash_id,
        ANY_VALUE(content_visible_query_count) AS visible_query_count,
        MAX(impressions_90d)
            / NULLIF(SUM(impressions_90d), 0) AS top_query_share
    FROM {TABLES['fact_query_90d']}
    GROUP BY content_hash_id
),

content_age AS (
    SELECT
        content_hash_id,
        DATE_DIFF(
            'day',
            CAST(content_created_date AS DATE),
            DATE '2026-03-01'
        ) AS age_days
    FROM {TABLES['dim_content']}
    WHERE content_created_date IS NOT NULL
)

SELECT
    p.client_hash_id,
    p.content_hash_id,

    p.previous_30d_impressions,
    p.previous_30d_clicks,
    p.previous_30d_avg_position,

    q.visible_query_count,
    q.top_query_share,

    a.age_days,

    m.march_impressions

FROM previous_window p

LEFT JOIN march_window m
    ON p.client_hash_id = m.client_hash_id
   AND p.content_hash_id = m.content_hash_id

LEFT JOIN query_signals q
    ON p.content_hash_id = q.content_hash_id

LEFT JOIN content_age a
    ON p.content_hash_id = a.content_hash_id

WHERE p.previous_30d_impressions > 0
  AND m.march_impressions IS NOT NULL
""").df()

print("March modeling rows:", len(march_data))
march_data.head()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

March modeling rows: 134238

,client_hash_id,content_hash_id,previous_30d_impressions,previous_30d_clicks,previous_30d_avg_position,visible_query_count,top_query_share,age_days,march_impressions
0,client_08a6a72ff48e62c0,content_95991e493be7daea,3332.0,4.0,7.356512,28,0.126202,163,3218.0
1,client_08a6a72ff48e62c0,content_959fc7aa6b4aadc2,10.0,0.0,27.566667,3,0.761468,320,72.0
2,client_08a6a72ff48e62c0,content_95ba6de2bc2a794c,50.0,0.0,18.459615,3,0.520000,320,95.0
3,client_08a6a72ff48e62c0,content_95be7a732080b5cc,1309.0,1.0,21.177232,12,0.172269,214,813.0
4,client_08a6a72ff48e62c0,content_95c314ab78eabcf4,3.0,0.0,6.250000,2,0.617647,209,40.0

In [ ]:
march_data["is_declining"] = (
    march_data["march_impressions"]
    < 0.80 * march_data["previous_30d_impressions"]
).astype(int)

print("Target distribution:")
print(march_data["is_declining"].value_counts())

print("\nTarget rate:")
print(round(march_data["is_declining"].mean(), 4))

Target distribution:
is_declining
0    107413
1     26825
Name: count, dtype: int64

Target rate:
0.1998

In [ ]:
print("Missing values in model features:")
print(march_data[feature_cols].isna().sum())

Missing values in model features:
previous_30d_impressions         0
previous_30d_clicks              0
previous_30d_avg_position        0
visible_query_count          49246
top_query_share              49246
age_days                         0
dtype: int64

In [ ]:
print("Rows:", len(march_data))
print("Clients:", march_data["client_hash_id"].nunique())
print("Declining:", march_data["is_declining"].sum())
print("Not declining:", (march_data["is_declining"] == 0).sum())

Rows: 134238
Clients: 42
Declining: 26825
Not declining: 107413

In [ ]:
from sklearn.model_selection import GroupShuffleSplit

X = march_data[feature_cols].copy()
y = march_data["is_declining"].copy()
groups = march_data["client_hash_id"]

splitter = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx, test_idx = next(
    splitter.split(X, y, groups=groups)
)

X_train = X.iloc[train_idx].copy()
X_test = X.iloc[test_idx].copy()

y_train = y.iloc[train_idx].copy()
y_test = y.iloc[test_idx].copy()

train_clients = groups.iloc[train_idx]
test_clients = groups.iloc[test_idx]

print("Training rows:", len(X_train))
print("Test rows:", len(X_test))

print("\nTraining clients:", train_clients.nunique())
print("Test clients:", test_clients.nunique())

print("\nDecline rate - train:", round(y_train.mean(), 4))
print("Decline rate - test:", round(y_test.mean(), 4))

print(
    "\nClient overlap:",
    len(set(train_clients) & set(test_clients))
)

Training rows: 88344
Test rows: 45894

Training clients: 33
Test clients: 9

Decline rate - train: 0.1796
Decline rate - test: 0.2387

Client overlap: 0

In [ ]:
# Calculate fill values using TRAINING data only
fill_values = X_train.median(numeric_only=True)

X_train = X_train.fillna(fill_values)
X_test = X_test.fillna(fill_values)

print("Missing values after filling - train:")
print(X_train.isna().sum())

print("\nMissing values after filling - test:")
print(X_test.isna().sum())

Missing values after filling - train:
previous_30d_impressions     0
previous_30d_clicks          0
previous_30d_avg_position    0
visible_query_count          0
top_query_share              0
age_days                     0
dtype: int64

Missing values after filling - test:
previous_30d_impressions     0
previous_30d_clicks          0
previous_30d_avg_position    0
visible_query_count          0
top_query_share              0
age_days                     0
dtype: int64

In [ ]:
print("Final training shape:", X_train.shape)
print("Final test shape:", X_test.shape)

print("\nTraining target:")
print(y_train.value_counts())

print("\nTest target:")
print(y_test.value_counts())

Final training shape: (88344, 6)
Final test shape: (45894, 6)

Training target:
is_declining
0    72475
1    15869
Name: count, dtype: int64

Test target:
is_declining
0    34938
1    10956
Name: count, dtype: int64

## 3. Train + compare vs my baseline

*Same data, same metric, same split as your Week-4 baseline. Show the table.*

## 3. Train + compare vs my baseline

I will train a Random Forest classifier using the six pre-decision features. The model will predict the probability of a meaningful impression decline.

Because the Week-4 baseline produces a continuous ranking score rather than a binary prediction, I will compare the baseline score and the model's predicted decline probability using Average Precision on the same held-out test clients.

This comparison keeps the evaluation population, target, and metric the same for both approaches. The purpose is to determine whether the learned model provides better ranking of likely declining content than the simple Week-4 rule.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import average_precision_score, roc_auc_score

model = RandomForestClassifier(
    n_estimators=200,
    max_depth=8,
    min_samples_leaf=10,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

model_probability = model.predict_proba(X_test)[:, 1]

print("Random Forest trained successfully.")
print("Number of trees:", model.n_estimators)
print("Test predictions:", len(model_probability))

Random Forest trained successfully.
Number of trees: 200
Test predictions: 45894

In [ ]:
baseline_test = X_test.copy()

baseline_test["score"] = 0

# Meaningful search visibility
baseline_test.loc[
    baseline_test["previous_30d_impressions"] >= 100,
    "score"
] += 40

# Older content gets supporting points
baseline_test.loc[
    baseline_test["age_days"] >= 365,
    "score"
] += 30

baseline_test.loc[
    (baseline_test["age_days"] >= 180) &
    (baseline_test["age_days"] < 365),
    "score"
] += 15

# Reasonable search position
baseline_test.loc[
    baseline_test["previous_30d_avg_position"] <= 20,
    "score"
] += 20

# Visible queries
baseline_test.loc[
    baseline_test["visible_query_count"] >= 5,
    "score"
] += 10

baseline_score = baseline_test["score"].to_numpy()

print("Baseline scores calculated.")
print("Minimum score:", baseline_score.min())
print("Maximum score:", baseline_score.max())

Baseline scores calculated.
Minimum score: 0
Maximum score: 100

In [ ]:
baseline_ap = average_precision_score(
    y_test,
    baseline_score
)

model_ap = average_precision_score(
    y_test,
    model_probability
)

baseline_auc = roc_auc_score(
    y_test,
    baseline_score
)

model_auc = roc_auc_score(
    y_test,
    model_probability
)

comparison = pd.DataFrame({
    "method": [
        "Week-4 baseline",
        "Random Forest"
    ],
    "average_precision": [
        baseline_ap,
        model_ap
    ],
    "roc_auc": [
        baseline_auc,
        model_auc
    ]
})

comparison

            method  average_precision   roc_auc
0  Week-4 baseline           0.224712  0.470661
1    Random Forest           0.411937  0.730861

In [ ]:
if model_ap > baseline_ap:
    print("Random Forest has higher Average Precision than the Week-4 baseline.")
elif model_ap < baseline_ap:
    print("Week-4 baseline has higher Average Precision than Random Forest.")
else:
    print("The model and baseline have the same Average Precision.")

print("\nBaseline AP:", round(baseline_ap, 4))
print("Random Forest AP:", round(model_ap, 4))

Random Forest has higher Average Precision than the Week-4 baseline.

Baseline AP: 0.2247
Random Forest AP: 0.4119

In [ ]:
importance = pd.DataFrame({
    "feature": feature_cols,
    "importance": model.feature_importances_
}).sort_values(
    "importance",
    ascending=False
)

importance

                     feature  importance
3        visible_query_count    0.234711
5                   age_days    0.234222
0   previous_30d_impressions    0.227151
4            top_query_share    0.194087
2  previous_30d_avg_position    0.066895
1        previous_30d_clicks    0.042934

## 4. Errors and interpretation

*Where is the model wrong? What does it lean on? A short error analysis beats a big metric table.*

## 4. Errors and interpretation

## 4. Errors and interpretation

On the held-out client test set, the Random Forest achieved an Average Precision of 0.4112 compared with 0.2247 for the Week-4 baseline. At a 0.50 probability threshold, the model produced 9,648 false positives and 4,339 false negatives, showing that some predictions remain uncertain.

The model relied most on visible_query_count (feature importance 0.2446), followed by age_days and previous_30d_impressions. These importance values describe how the model used the available signals and should not be interpreted as causal effects.

The errors show why the model should be used as decision-support rather than automatic action. A content team should review high-scoring recommendations in context, especially where the model is uncertain or where the available six features do not capture other factors affecting performance.

In [ ]:
error_analysis = X_test.copy()

error_analysis["actual"] = y_test.to_numpy()
error_analysis["predicted_probability"] = model_probability

error_analysis["prediction_error"] = (
    error_analysis["predicted_probability"]
    - error_analysis["actual"]
)

error_analysis.head()

,previous_30d_impressions,previous_30d_clicks,previous_30d_avg_position,visible_query_count,top_query_share,age_days,actual,predicted_probability,prediction_error
588,914.0,4.0,6.364955,24,0.208478,12,0,0.026481,0.026481
589,33.0,0.0,23.907143,7,0.360294,5,0,0.118617,0.118617
590,180.0,4.0,3.622153,8,0.411765,5,0,0.037471,0.037471
591,35.0,0.0,3.034091,1,1.000000,5,1,0.074703,-0.925297
592,27.0,0.0,5.509259,2,0.518519,13,0,0.054333,0.054333

In [ ]:
false_positives = error_analysis[
    error_analysis["actual"] == 0
].sort_values(
    "predicted_probability",
    ascending=False
)

print("Top false positives:")
false_positives.head(10)

Top false positives:

,previous_30d_impressions,previous_30d_clicks,previous_30d_avg_position,visible_query_count,top_query_share,age_days,actual,predicted_probability,prediction_error
55301,5067.0,10.0,6.666945,16,0.257157,417,0,0.767901,0.767901
55031,4581.0,5.0,3.483841,15,0.328020,417,0,0.766810,0.766810
79568,3167.0,4.0,9.169462,12,0.194595,417,0,0.741482,0.741482
101005,346.0,0.0,0.124910,7,0.367925,213,0,0.739480,0.739480
130926,24.0,0.0,0.071429,7,0.367925,213,0,0.739324,0.739324
124491,101.0,0.0,0.305455,7,0.367925,230,0,0.737990,0.737990
106830,117.0,0.0,0.567901,7,0.367925,229,0,0.737990,0.737990
101015,278.0,0.0,0.661701,7,0.367925,158,0,0.737648,0.737648
115274,25.0,0.0,0.361111,7,0.367925,213,0,0.737375,0.737375
91441,45.0,0.0,0.658730,7,0.367925,229,0,0.737181,0.737181

In [ ]:
false_negatives = error_analysis[
    error_analysis["actual"] == 1
].sort_values(
    "predicted_probability",
    ascending=True
)

print("Top false negatives:")
false_negatives.head(10)

Top false negatives:

,previous_30d_impressions,previous_30d_clicks,previous_30d_avg_position,visible_query_count,top_query_share,age_days,actual,predicted_probability,prediction_error
27087,843.0,3.0,4.454836,59,0.172678,19,1,0.007434,-0.992566
3233,1106.0,5.0,2.278223,42,0.221858,13,1,0.009824,-0.990176
69820,752.0,6.0,5.619659,57,0.074536,19,1,0.012638,-0.987362
593,1045.0,12.0,4.022047,76,0.266254,5,1,0.014572,-0.985428
42932,1135.0,6.0,5.120749,36,0.200847,5,1,0.016150,-0.983850
72695,567.0,7.0,6.585382,25,0.131610,19,1,0.019970,-0.980030
47364,417.0,2.0,3.186388,17,0.301483,5,1,0.021335,-0.978665
1159,1758.0,7.0,4.959704,31,0.068908,19,1,0.023112,-0.976888
45524,554.0,5.0,3.558021,56,0.385070,5,1,0.024901,-0.975099
985,793.0,3.0,6.563987,29,0.097210,19,1,0.025154,-0.974846

In [ ]:
uncertain_cases = error_analysis.copy()

uncertain_cases["distance_from_half"] = abs(
    uncertain_cases["predicted_probability"] - 0.5
)

uncertain_cases = uncertain_cases.sort_values(
    "distance_from_half"
)

print("Most uncertain predictions:")
uncertain_cases.head(10)

Most uncertain predictions:

,previous_30d_impressions,previous_30d_clicks,previous_30d_avg_position,visible_query_count,top_query_share,age_days,actual,predicted_probability,prediction_error,distance_from_half
10813,434.0,0.0,1.372986,3,0.434783,230,0,0.499993,0.499993,0.000007
90831,345.0,2.0,10.224976,7,0.367925,17,1,0.499986,-0.500014,0.000014
49868,297.0,1.0,7.629276,2,0.593750,382,0,0.500023,0.500023,0.000023
78478,3258.0,6.0,7.471373,17,0.279248,380,0,0.499975,0.499975,0.000025
52727,1070.0,1.0,4.498387,5,0.465784,341,1,0.499955,-0.500045,0.000045
13549,288.0,0.0,8.870062,3,0.475410,262,1,0.500047,-0.499953,0.000047
8243,1160.0,1.0,6.185688,6,0.351266,341,0,0.499934,0.499934,0.000066
18780,47.0,1.0,42.814444,1,1.000000,198,0,0.500069,0.500069,0.000069
7863,477.0,2.0,6.384677,3,0.465517,289,0,0.500084,0.500084,0.000084
80562,1709.0,1.0,6.041284,6,0.217391,366,1,0.500095,-0.499905,0.000095

In [ ]:
# Use 0.50 only for a simple error-count view.
# The main model comparison above remains Average Precision,
# because this is a ranking problem.

error_analysis["predicted_class"] = (
    error_analysis["predicted_probability"] >= 0.50
).astype(int)

false_positives_count = (
    (error_analysis["predicted_class"] == 1) &
    (error_analysis["actual"] == 0)
).sum()

false_negatives_count = (
    (error_analysis["predicted_class"] == 0) &
    (error_analysis["actual"] == 1)
).sum()

true_positives_count = (
    (error_analysis["predicted_class"] == 1) &
    (error_analysis["actual"] == 1)
).sum()

true_negatives_count = (
    (error_analysis["predicted_class"] == 0) &
    (error_analysis["actual"] == 0)
).sum()

print("Error analysis summary")
print("----------------------")
print("False positives:", false_positives_count)
print("False negatives:", false_negatives_count)
print("True positives:", true_positives_count)
print("True negatives:", true_negatives_count)

print(
    "\nMost important feature:",
    importance.iloc[0]["feature"]
)

print(
    "Most important feature importance:",
    round(importance.iloc[0]["importance"], 4)
)

Error analysis summary
----------------------
False positives: 9596
False negatives: 4355
True positives: 6601
True negatives: 25342

Most important feature: visible_query_count
Most important feature importance: 0.2347

In [ ]:
print("Final model vs baseline:")
print(comparison)

print("\nFeature importance:")
print(importance)

print("\nError counts at probability threshold 0.50:")
print("False positives:", false_positives_count)
print("False negatives:", false_negatives_count)
print("True positives:", true_positives_count)
print("True negatives:", true_negatives_count)

Final model vs baseline:
            method  average_precision   roc_auc
0  Week-4 baseline           0.224712  0.470661
1    Random Forest           0.411937  0.730861

Feature importance:
                     feature  importance
3        visible_query_count    0.234711
5                   age_days    0.234222
0   previous_30d_impressions    0.227151
4            top_query_share    0.194087
2  previous_30d_avg_position    0.066895
1        previous_30d_clicks    0.042934

Error counts at probability threshold 0.50:
False positives: 9596
False negatives: 4355
True positives: 6601
True negatives: 25342

## Self-check

- [x] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [x] No client names, URLs, or private queries anywhere
- [x] My claims use careful words: observed, measured, directional, decision-support
- [x] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done